name: Auto-publish Release

# Event to only execute when a push on master branch has occured.
on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Get the release version
      uses: cycjimmy/semantic-release-action@v2
      id: semantic 
      # Environment Variables
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
        # TAG: v$RELEASE_VERSION
      with:
        # You can specify specifying version range for the extra plugins if you prefer.
        extra_plugins: |
          @semantic-release/changelog@3.0.0
          @semantic-release/git
      run: echo ${{ steps.semantic.outputs.release-version }}
      run: echo "$OUTPUTS"  

    - name: Do something when a new release published
      if: steps.semantic.outputs.new_release_published == 'true'
      run: echo ${{ steps.semantic.outputs.new_release_version }}
